# Based on https://github.com/NixOS/nixpkgs/blob/master/.travis.yml and
# https://github.com/NixOS/nixpkgs/blob/master/maintainers/scripts/travis-nox-review-pr.sh

language: c
sudo: required
dist: trusty

before_install:
 - export NIX_CURL_FLAGS=-sS
 - echo "=== Installing Nix..."
 - bash <(curl -sS https://nixos.org/nix/install)
 - source $HOME/.nix-profile/etc/profile.d/nix.sh
 - sudo mkdir /etc/nix
 - |
   echo "binary-caches = http://cache.nixos.org http://hydra.nixos.org
   trusted-binary-caches = http://hydra.nixos.org
   build-max-jobs = 4" | sudo tee /etc/nix/nix.conf > /dev/null
 - nix-env -i stack
 - stack --nix --no-nix-pure setup

install:
 - true

script:
 - stack --nix test

