flags: {}
nix:
  packages:
  - llvm_4

extra-package-dbs: []

packages:
- location: jael/

extra-deps:
- git: https://github.com/ucsd-progsys/liquid-fixpoint
  commit: d84bf9e36bc3888b149a5fc9e8d23c5545070803
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.1.4
- located-base-0.1.1.0

resolver: lts-9.14
