resolver: lts-5.9

nix:
  enable: false
  packages:
   # To fetch liquid-fixpoint dependency
   - git
   # Build deps
   - llvm_35

packages:
- location: ./jael/
- location: ./jael-grammar/

extra-deps:
# Jael-grammar setup dependency
- BNFC-2.8.1
# Jael deps
- liquid-fixpoint-0.5.0.1
- llvm-general-3.5.1.2
- llvm-general-pure-3.5.1.0
# Pulled in by liquid-fixpoint
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.1.4
- located-base-0.1.1.0
