flags: {}
nix:
  packages:
  - gcc
  - git
  - haskellPackages.alex
  - haskellPackages.BNFC
  - haskellPackages.happy
  - llvm
  - ncurses
  - zlib
extra-package-dbs: []
packages:
- location: jael/
- location: jael-grammar/
- location:
    git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: 6141e5ae445bfc2ff37a93f54fad3c0f020a634a
  extra-dep: true
- location:
    git: https://github.com/bscarlet/llvm-general
    commit: ec1ad5bd2112e7f64dbb43441b5e2075cf6ad8e7
  subdirs:
  - llvm-general
  - llvm-general-pure
  extra-dep: true
extra-deps:
  #- BNFC-2.8.1
- bifunctors-5.4.1
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.1.4
- located-base-0.1.1.0
- recursion-schemes-5
- semigroupoids-5.1
- transformers-compat-0.5.1.4
- unix-compat-0.4.3.1
#resolver: lts-7.14
resolver: lts-6.26
