resolver: nightly-2017-10-06

flags: {}
nix:
  enable: false
  packages:
  - llvm_4

extra-package-dbs: []

packages:
- location: .

extra-deps:
- git: https://github.com/ucsd-progsys/liquid-fixpoint
  commit: aba45f75b7d90a9c1980b835fe1b65ccb61dae4f
- base-noprelude-4.10.1.0
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- intern-0.9.1.4
- located-base-0.1.1.1

allow-newer: true
