= The Jael Guide
:toc: preamble

toc::[]

== Introduction

Jael is a _domain specific language_ for writing reliable, low-level embedded software. By focusing on a specific domain, restrictions can be placed on the software to achieve goals that would be difficult or impossible to achieve in a general purpose programming language. Jael attempts to explore how various features can be incorporated to achieve embedded specific goals. At a high level, these goals include:

* statically eliminating run-time errors
* statically preventing infinite loops, race conditions, and deadlocks
* statically determining the upper bound on memory usage

Jael places an emphasis on identifying these issues statically. There are several reasons why this is desirable when developing embedded software, for example:

* debugging tools are often less capable than those on desktop systems (often times, low-cost processors will have no on-chip debugging capabilities)
* embedded software may operate remotely making servicing malfunctioning software difficult
* embedded software may be used in situations where software malfunctions can have an extremely high impact (e.g., in medical devices or aeronautics and vehicle components)

=== Intended Audience

Jael is not a typical programming language and as such, many of the concepts may seem foreign to embedded software developers. The purpose of this document is to introduce Jael to such people. Where applicable, features and concepts will be compared to what is typical of low-level embedded software, namely *C*. As such, a basic familiarity with *C* is assumed.

Concepts and syntax will be introduced sequentially in a way such that the next section depends on the previous one. Therefore, it is recommended that this document be read top to bottom.

=== Design

There are three distinct aspects of Jael, each of which address certain issues and achieve specific goals. Throughout this document, these components will be referred to the _sequential language (SL)_, the _concurrent language (CL)_, and the _memory description language (MDL)_ (name subject to change). These sub-languages build on one another: the concurrent language depends on the sequential language, and the memory description language depends on both the concurrent and sequential languages. As such, these components will be presented in that order in this guide.

== Sequential Computation

At the lowest level is SL, the language for expressing sequential computations. This language is the most similar of Jael's three components to other programming languages. Syntactically it feels somewhat like *C*, however there are significant differences in how SL operates and what it is capable of.

=== Pure and Total

Unlike *C*, SL is a pure and total functional language. To be a pure functional language means that functions have no state and all data is immutable (it is functional in a mathematical sense just as the function `f(x)=x^2^` can not mutate `x` nor any global state). There are several consequence of this that distinguish pure functional languages from imperative ones:

* functions are uniquely determined by their inputs (that is, for the same inputs, a function will always return the same value)
* unlike imperative languages, it does not make sense for a function to not return a value (with no state or mutability, a function that does not return a value has no way to communicate what it computed)
* if the result of a function call is not used, the function never needs to be called (because there are no side effects)
* a pure function can not communicate with the outside world; there can be no arbitrary memory access, meaning no pointers (this implies some global state is read or written)

The predictable behaviour of a pure functional language makes it easier to reason about what a piece of code does. However, without state or a way to communicate with the outside world, pure computation is of limited use: it simply computes data from other data. We will see how state and non-determinism is handled when we discuss the CL and MDL.

SL is also a total language. This means that all functions will return a value for all valid inputs. The opposite of being total is to be partial. For example, division is inherently partial (or non-total) because it is undefined when the denominator is zero. Several things need to be considered in order to achieve totality. These are discussed in the sections <<Type Refinements>> and <<Restrictions>>.

=== Types

==== Built-in Types

==== Structures

==== Enumerations

=== Expressions

=== Functions

==== Defining

==== Built-in functions

=== Type Inference

=== Type Refinements

=== Restrictions

== Concurrent Computation

=== Process Model

=== Sessions (Protocols)

=== Linearity

== Accessing and Modelling Memory

== Syntax Reference

== References
